In [69]:
#Numpy

This is an example for markdown

In [2]:
# NUmpy Basics

In [3]:
import numpy as np

In [4]:
list1 = [1,2,3,4]

In [5]:
np.array(list1)

array([1, 2, 3, 4])

In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([1, 2, 3, 4])

In [12]:
np.arange(0,60,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [13]:
np.arange(26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.linspace(0,50,99)

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ,
       25.51020408, 26.02040816, 26.53061224, 27.04081633, 27.55102041,
       28.06122449, 28.57142857, 29.08163265, 29.59183673, 30.10204082,
       30.6122449 , 31.12244898, 31.63265306, 32.14285714, 32.65306122,
       33.16326531, 33.67346939, 34.18367347, 34.69387755, 35.20

In [31]:
np.random.rand(7)

array([0.98666632, 0.64248371, 0.76231803, 0.2124434 , 0.59782661,
       0.88733223, 0.85092623])

In [33]:
np.random.rand(9)

array([0.95056682, 0.81986053, 0.89781118, 0.39213305, 0.1414346 ,
       0.19094363, 0.04348324, 0.81764491, 0.68818112])

In [38]:
np.random.randn(9)

array([ 0.56860416, -1.06420747, -0.02040055,  1.76562385, -0.7061177 ,
       -0.24536394, -1.14225001,  0.00859032,  1.82013319])

In [39]:
np.random.randint(10,1000,70)

array([ 39, 419, 309, 242, 937, 215, 178, 615, 237, 171, 550,  36, 963,
       878, 421, 786, 877, 375, 629, 721, 439, 343, 430, 480, 858, 759,
       304, 149, 163, 303, 525, 420, 468,  42, 307, 510, 571, 626, 934,
       575, 918, 776, 353, 787, 986, 492, 278, 734, 536, 232, 142, 643,
       413, 594, 582, 987, 640, 663, 795,  18, 223,  14, 761, 344, 804,
       547, 149, 256, 341, 178])

In [40]:
np.random.randint(0,199999,2)

array([127248,  26635])

BELOW CELLS ARE METHODS!!

In [41]:
# Methods

In [42]:
example_arr = np.arange(25)

In [43]:
example_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
random_arr = np.random.randint(0,100,26)


In [56]:
random_arr

array([54, 38,  7, 63, 87, 42, 41, 80,  1, 89, 77, 10, 46, 77, 47, 48, 42,
       40, 61, 28, 75,  2,  5, 37, 93, 29])

In [57]:
random_arr.max()

93

In [58]:
random_arr.min()

1

In [59]:
random_arr.argmax()

24

In [60]:
random_arr.argmin()

8

In [61]:
random_arr.shape

(26,)

In [63]:
random_arr.reshape(13,2)

array([[54, 38],
       [ 7, 63],
       [87, 42],
       [41, 80],
       [ 1, 89],
       [77, 10],
       [46, 77],
       [47, 48],
       [42, 40],
       [61, 28],
       [75,  2],
       [ 5, 37],
       [93, 29]])

In [64]:
random_arr.reshape(2,13)

array([[54, 38,  7, 63, 87, 42, 41, 80,  1, 89, 77, 10, 46],
       [77, 47, 48, 42, 40, 61, 28, 75,  2,  5, 37, 93, 29]])

In [65]:
random_arr.reshape(26,1)

array([[54],
       [38],
       [ 7],
       [63],
       [87],
       [42],
       [41],
       [80],
       [ 1],
       [89],
       [77],
       [10],
       [46],
       [77],
       [47],
       [48],
       [42],
       [40],
       [61],
       [28],
       [75],
       [ 2],
       [ 5],
       [37],
       [93],
       [29]])

In [66]:
random_arr.reshape(1,26)

array([[54, 38,  7, 63, 87, 42, 41, 80,  1, 89, 77, 10, 46, 77, 47, 48,
        42, 40, 61, 28, 75,  2,  5, 37, 93, 29]])

In [68]:
random_arr.dtype

dtype('int32')